Added Notifications and Notification Settings Services
j2inn/haystack-nclient pull request #14
Opened 2022-06-29 16:10 UTC by thoughtpalette

Added Notification Services to allow the developer to interact with the Notifications APIs

2022-06-30 08:03 UTC, garethj2 requested changes

2022-06-30 08:03 UTC, garethj2 commented on package.json
> +	"version": "3.0.19",
When creating a github release, this version is automatically incremented by the CI/CD pipeline.

Please note, to publish a new version of haystack-nclient one just needs to create a new release. The pipeline takes care of verifying/publishing it.

2022-06-30 08:03 UTC, garethj2 commented on src/client/notifications/NotificationService.ts
> +		if (notifications.isEmpty()) {
I'm not sure this if statement returning an empty array is needed. Surely the notifications.toArray will just return an empty array if there are no notifications.

The same applies below with some of the other methods.

2022-06-30 08:03 UTC, garethj2 commented on src/client/ClientServiceConfig.ts
> +	 * Return the URL for a general REST service/
Nitpik: full stop at end instead of slash.

2022-06-30 08:03 UTC, garethj2 commented on src/client/ClientServiceConfig.ts
> +	getOriginApiUrl(path: string): string
Should we change this to getServiceUrl? I think it'll fit in better alongside getHostServiceUrl and getHaystackServiceUrl.

2022-06-30 08:03 UTC, garethj2 commented on src/util/http.ts
> +	apiName,
Prefer `path` over `apiName`. This matches the other methods.

2022-06-30 08:03 UTC, garethj2 commented on src/client/notifications/NotificationService.ts
> +	NotificationType extends Notification = Notification
I see you're just trying to keep this to the REST APIs but I don't think this service is that useful without the automatic polling and EventSource implementation.

See the WatchService methods for how this could be implemented...

* Calling `make` on the `NotificationsService` will asynchronously return a `Notifications` object. The `Notifications` object can either poll or register itself to receive events.
* The `Notifications` object can have event listeners registered and unregistered - again using the similar design to `Watch` but not as complex. For example, a `Notifications` object doesn't need to hold data like a Watch does. It's just an event emitter.

2022-06-30 08:03 UTC, garethj2 commented on src/client/notifications/NotificationSettingService.ts
> +export class NotificationSettingsService {
The name of the file is `NotificationSettingService.ts`. The name of the class is `NotificationSettingsService`. The file name `Setting` needs to be plural.

2022-06-30 08:03 UTC, garethj2 commented on src/client/notifications/NotificationService.ts
> +	readonly #serviceConfig: ClientServiceConfig
Unit tests are required. See other services.

2022-06-30 08:03 UTC, garethj2 commented on src/client/notifications/NotificationSettingService.ts
> +	/**
Unit tests are required. See other services.

2022-06-30 08:03 UTC, garethj2 commented on src/client/notifications/NotificationService.ts
> +				body: JSON.stringify(HDict.make(notification).toJSON()),
This could be simplified just to...

```
JSON.stringify(notification)
```

- The notification is already an HDict.
- The `JSON.stringify` method will find a `toJSON` method on `HDict` and will call that automatically for you.

2022-06-30 08:03 UTC, garethj2 commented on src/client/notifications/NotificationService.ts
> +				body: JSON.stringify(HDateTime.make(timeOfLastMod).toJSON()),
This can be simplified to...

```
JSON.stringify(timeOfLastMod)
```
The `timeOfLastMod` variable is already a `HDateTime` so there's no need to wrap it up again and call `toJSON`. See comment above for why `toJSON` doesn't need to be explicitly called.

2022-06-30 08:03 UTC, garethj2 commented on src/client/notifications/NotificationSettingService.ts
> +	public async readTopics<T extends HVal>(): Promise<T[]> {
Should this really be a generic parameter? Surely by default this should be one of the interface types you've got list above (i.e. TopicDescription).

The same applies to the other methods in this class.

2022-06-30 15:07 UTC, thoughtpalette commented on package.json
> +	"version": "3.0.19",
Reverted manual version update.

2022-06-30 15:07 UTC, thoughtpalette commented on src/client/notifications/NotificationService.ts
> +		if (notifications.isEmpty()) {
Removed superfluous empty arr returns.

2022-06-30 15:07 UTC, thoughtpalette commented on src/client/ClientServiceConfig.ts
> +	getOriginApiUrl(path: string): string
Sounds good, updated references.

2022-06-30 15:08 UTC, thoughtpalette commented on src/client/notifications/NotificationService.ts
> +				body: JSON.stringify(HDict.make(notification).toJSON()),
Makes sense. I was following the convention in UserService. We may want to update those was well.

2022-06-30 15:09 UTC, thoughtpalette commented on src/client/notifications/NotificationSettingService.ts
> +	public async readTopics<T extends HVal>(): Promise<T[]> {
Updated to use their types.

2022-07-27 16:03 UTC, rracariu approved these changes
LGTM

2022-07-28 14:43 UTC, merged