Enhancement/attest key request headers
j2inn/haystack-nclient pull request #16
Opened 2022-07-09 02:43 UTC by EliteScientist

Removed invalid attest key header before requesting a new one. It was observed that when the old attest key was in the header while requesting a new one, this caused a remote system to terminate the connection.

2022-07-11 08:09 UTC, garethj2 requested changes

2022-07-11 08:09 UTC, garethj2 commented on src/util/http.ts
> +export function removeHeader(
A unit tests needs to be added for the `remoteHeader` function.

2022-07-11 16:04 UTC, EliteScientist commented on src/util/http.ts
> +export function removeHeader(
Good Catch!

2022-07-12 08:21 UTC, garethj2 approved these changes

2022-07-12 19:53 UTC, merged