Scheduler Service - Implemented updated REST API and Types
j2inn/haystack-nclient pull request #28
Opened 2023-05-10 16:03 UTC by thoughtpalette

This PR adds the following functionality:
- Updates Schedule Service to use newly define REST API endpoints.
- Updates Type Definitions utilized in the schedule service.
- Updates tests with the updated Record mocks and endpoints.

@hecsalazarf Please take extra care when reviewing the Type schemas. I attempted to extract them from the OpenAPI docs as best I could and it's important for implementation that these match as best as possible.

---

![Screenshot 2023-05-10 at 11 02 20 AM](https://github.com/j2inn/haystack-nclient/assets/690624/4609b904-ed30-4e9d-9080-fd71c18f1cfa)

2023-05-10 21:14 UTC, hecsalazarf requested changes
Looks good, just comments for minor changes to support key scheduler features.

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/ScheduleService.ts
> +	public async createSchedules(schedules: Schedule | HDict | HGrid) {
Since `Schedule` extends `HDict`, param type could be `Schedule | HGrid<Schedule>`. What do you think?

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/ScheduleService.ts
> +	public async updateSchedule(schedule: Schedule) {
Partial updates are supported; `Schedule` type would enforce to send all mandatory fields. We could pass a plain `HDict` or make use of [Partial](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype). I think `HDict` is better because we could remove tags with `HRemove`.

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/ScheduleService.ts
> +	public async createCalendars(calendars: Calendar | HDict | HGrid) {
Same case as with schedules: `Calendar | HGrid<Calendar>`?

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/ScheduleService.ts
> +	public async updateCalendar(calendar: Calendar) {
Partial updates are also supported for calendars.

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/types.ts
> +export interface Schedule extends HDict {
Time zone (`tz`) is missing.

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/types.ts
> +		hour: number
`bacnetTime` props should be all optional to allow wildcards.

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/types.ts
> +	weeklySchedule?: WeekDaySchedule[]
To keep consistency with the Haystack model, do you think arrays could be replaced with `HList`s?

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/types.ts
> +	scheduledVal: HVal
Scheduled values accept `null`. It's probably better to use `OptionalHVal ` (applies for all `HVal` props).

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/types.ts
> +export interface CalendarDate {
All props should be optional due to wildcards.

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/types.ts
> +export interface CalendarWeekNDay {
Same case, props should be optional.

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/types.ts
> +	nthWeek: number
According to the BACnet spec, this is `weekOfMonth`. I think we should keep the same name.

2023-05-10 21:14 UTC, hecsalazarf commented on src/client/schedules/types.ts
> +	dayOfWeek: number
`month` is missing. `CalendarWeekNDay` has three components: `dayOfWeek`, `weekOfMonth` and `month`.

2023-05-11 13:34 UTC, thoughtpalette commented on src/client/schedules/ScheduleService.ts
> +	public async createSchedules(schedules: Schedule | HDict | HGrid) {
Works for me! I was leaving it a little flexible here, but since we're exporting the Type, I think we can safely assume the shape to be Schedule.

2023-05-11 14:02 UTC, thoughtpalette commented on src/client/schedules/types.ts
> +export interface Schedule extends HDict {
Added required `tz: HStr` prop

2023-05-11 14:10 UTC, thoughtpalette commented on src/client/schedules/types.ts
> +	weeklySchedule?: WeekDaySchedule[]
Replaced all arrays with `HList<T>`

2023-05-11 14:12 UTC, thoughtpalette commented on src/client/schedules/types.ts
> +	scheduledVal: HVal
Updated all `HVals` to use `OptionalHVal`

2023-05-11 14:16 UTC, thoughtpalette commented
@hecsalazarf Thanks for your comments! I've made the requested changes. Please feel free to take another look when you have the opportunity.

2023-05-11 14:21 UTC, hecsalazarf approved these changes

2023-05-11 14:23 UTC, merged